# Generated by Django 4.0 on 2022-01-25 13:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nft',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creator_network', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('creator_wallet_id', models.UUIDField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('external_link', models.CharField(max_length=1000)),
                ('collection', models.UUIDField(null=True, unique=True)),
                ('supply', models.IntegerField(default=1)),
                ('royalties', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.nft')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
