# Generated by Django 4.0 on 2022-01-25 13:55
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='creator',
            new_name='nft',
        ),
    ]
